### PR TITLE
functionality to change theme

### LINKED ISSUE #18: [Feature] Adding change theme color button
Option to change theme color button(from green to red) just like dark mode/light mode button

### PR DESCRIPTION
**Pull request by vinay-pseudo**
fixes #18 
added functionality to the change theme color button

### CODE REVIEW

**Comment by Anisha7860** [comment]
Screenshot_20221005_175829
Check this out

**Comment by vinay-pseudo** [comment]
This is because I've made changes in those files to add the functionality. You can resolve the conflicts by merging the code and then the pull request can be accepted.

**Comment by Anisha7860** [comment]
It will be good if you can resolve the conflicts , am quite busy with other
work

**Comment by vinay-pseudo** [comment]
I resolved the conflicts. You can merge now

**Pull request merged**
